/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calls */
        get: operations["list_calls_api_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Call */
        get: operations["get_call_api_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/{call_id}/mark-handled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Handled */
        post: operations["mark_handled_api_calls__call_id__mark_handled_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/firma/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_firma_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/firma/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Settings */
        put: operations["update_settings_api_firma_me_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Address */
        Address: {
            /** Street */
            street: string;
            /** Apartment */
            apartment?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** City */
            city?: string | null;
            /**
             * Country
             * @default SE
             */
            country: string;
        };
        /** CallDetailRead */
        CallDetailRead: {
            /** Id */
            id: string;
            /** Customer Id */
            customer_id: string | null;
            /** Customer Name */
            customer_name: string | null;
            /** Caller Phone */
            caller_phone: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            intent: components["schemas"]["Intent"] | null;
            severity: components["schemas"]["Severity"] | null;
            status: components["schemas"]["CallStatus"];
            /** Summary Short */
            summary_short: string | null;
            summary: components["schemas"]["CallSummary"] | null;
            /** Transcript */
            transcript: components["schemas"]["TranscriptSegmentRead"][];
            /** Tool Invocations */
            tool_invocations: components["schemas"]["ToolInvocationRead"][];
            /** Recording Url */
            recording_url: string | null;
        };
        /** CallRead */
        CallRead: {
            /** Id */
            id: string;
            /** Customer Id */
            customer_id: string | null;
            /** Customer Name */
            customer_name: string | null;
            /** Caller Phone */
            caller_phone: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            intent: components["schemas"]["Intent"] | null;
            severity: components["schemas"]["Severity"] | null;
            status: components["schemas"]["CallStatus"];
            /** Summary Short */
            summary_short: string | null;
        };
        /**
         * CallStatus
         * @enum {string}
         */
        CallStatus: "in_progress" | "completed" | "handled" | "needs_followup";
        /** CallSummary */
        CallSummary: {
            /** Short Sv */
            short_sv: string;
            /** Long Sv */
            long_sv: string;
            /** Next Action Sv */
            next_action_sv: string;
            /** Owner Action Required */
            owner_action_required: boolean;
            /**
             * Structured Fields
             * @default {}
             */
            structured_fields: {
                [key: string]: unknown;
            };
        };
        /** CustomerRead */
        CustomerRead: {
            /** Id */
            id: string;
            type: components["schemas"]["CustomerType"];
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Org Number */
            org_number: string | null;
            address: components["schemas"]["Address"] | null;
            /** Notes Summary */
            notes_summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CustomerType
         * @enum {string}
         */
        CustomerType: "private" | "company";
        /** FirmaRead */
        FirmaRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Org Number */
            org_number: string | null;
            trade: components["schemas"]["Trade"];
            plan: components["schemas"]["Plan"];
            /** Locality */
            locality: string | null;
            settings: components["schemas"]["FirmaSettings"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FirmaSettings */
        FirmaSettings: {
            /**
             * Greeting Text
             * @default Hej, du har kommit till {firma_namn}, jag är deras digitala assistent. Hur kan jag hjälpa dig?
             */
            greeting_text: string;
            /**
             * Voice
             * @default Aoede
             */
            voice: string;
            /**
             * Open Hours Weekday
             * @default [
             *       "07:00",
             *       "17:00"
             *     ]
             */
            open_hours_weekday: [
                string,
                string
            ];
            /** Open Hours Saturday */
            open_hours_saturday?: [
                string,
                string
            ] | null;
            /** Open Hours Sunday */
            open_hours_sunday?: [
                string,
                string
            ] | null;
            /**
             * Answer Outside Hours
             * @default true
             */
            answer_outside_hours: boolean;
            /**
             * Record Calls
             * @default true
             */
            record_calls: boolean;
            /**
             * Recording Retention Days
             * @default 7
             */
            recording_retention_days: number;
            /**
             * Transcript Retention Days
             * @default 90
             */
            transcript_retention_days: number;
            /**
             * Persona Overrides
             * @default
             */
            persona_overrides: string;
        };
        /** FirmaSettingsUpdate */
        FirmaSettingsUpdate: {
            /** Greeting Text */
            greeting_text?: string | null;
            /** Voice */
            voice?: string | null;
            /** Open Hours Weekday */
            open_hours_weekday?: [
                string,
                string
            ] | null;
            /** Answer Outside Hours */
            answer_outside_hours?: boolean | null;
            /** Record Calls */
            record_calls?: boolean | null;
            /** Recording Retention Days */
            recording_retention_days?: number | null;
            /** Persona Overrides */
            persona_overrides?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Env */
            env: string;
            /** Version */
            version: string;
        };
        /**
         * Intent
         * @enum {string}
         */
        Intent: "akut" | "offertforfragan" | "bokning" | "befintlig_kund_fraga" | "ovrigt";
        /**
         * Plan
         * @enum {string}
         */
        Plan: "starter" | "professional" | "premium";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
        /** ToolInvocationRead */
        ToolInvocationRead: {
            /** Name */
            name: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error: string | null;
            /**
             * Invoked At
             * Format: date-time
             */
            invoked_at: string;
        };
        /**
         * Trade
         * @enum {string}
         */
        Trade: "vvs" | "el" | "snickeri" | "tak" | "kakel" | "ovrigt";
        /**
         * TranscriptRole
         * @enum {string}
         */
        TranscriptRole: "caller" | "ai" | "system";
        /** TranscriptSegmentRead */
        TranscriptSegmentRead: {
            role: components["schemas"]["TranscriptRole"];
            /** Text */
            text: string;
            /** Ts Ms Offset */
            ts_ms_offset: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_calls_api_calls_get: {
        parameters: {
            query?: {
                intent?: components["schemas"]["Intent"] | null;
                severity?: components["schemas"]["Severity"] | null;
                status?: components["schemas"]["CallStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Firma-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_api_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Firma-Id"?: string | null;
            };
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_handled_api_calls__call_id__mark_handled_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Firma-Id"?: string | null;
            };
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_customers_get: {
        parameters: {
            query?: {
                /** @description Free-text search on name/phone */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Firma-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Firma-Id"?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_firma_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Firma-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirmaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_firma_me_settings_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Firma-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FirmaSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirmaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
