"""Tables imported here so SQLModel.metadata.create_all() picks them up."""

from switchboard.models.audit import AuditLog, AuditLogRead
from switchboard.models.call import (
    Call,
    CallDetailRead,
    CallRead,
    CallSummary,
    ToolInvocation,
    ToolInvocationRead,
    TranscriptSegment,
    TranscriptSegmentRead,
)
from switchboard.models.customer import (
    Address,
    Customer,
    CustomerRead,
    Note,
    Photo,
)
from switchboard.models.enums import (
    CallStatus,
    CustomerType,
    EmergencyIndicator,
    EscalationStatus,
    IntegrationType,
    Intent,
    JobStatus,
    Plan,
    Severity,
    Trade,
    TranscriptRole,
)
from switchboard.models.escalation import Escalation, EscalationRead
from switchboard.models.firma import (
    EscalationChain,
    EscalationStep,
    Firma,
    FirmaRead,
    FirmaSettings,
    FirmaSettingsUpdate,
    Integration,
    PhoneNumber,
    User,
    UserFirmaMembership,
)
from switchboard.models.job import Job, JobRead

__all__ = [
    "Address",
    "AuditLog",
    "AuditLogRead",
    "Call",
    "CallDetailRead",
    "CallRead",
    "CallStatus",
    "CallSummary",
    "Customer",
    "CustomerRead",
    "CustomerType",
    "EmergencyIndicator",
    "Escalation",
    "EscalationChain",
    "EscalationRead",
    "EscalationStatus",
    "EscalationStep",
    "Firma",
    "FirmaRead",
    "FirmaSettings",
    "FirmaSettingsUpdate",
    "Integration",
    "IntegrationType",
    "Intent",
    "Job",
    "JobRead",
    "JobStatus",
    "Note",
    "PhoneNumber",
    "Photo",
    "Plan",
    "Severity",
    "ToolInvocation",
    "ToolInvocationRead",
    "Trade",
    "TranscriptRole",
    "TranscriptSegment",
    "TranscriptSegmentRead",
    "User",
    "UserFirmaMembership",
]
